version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    volumes:
      - .mqtt/MQTTBroker/config:/mosquitto/config
      - .mqtt/MQTTBroker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - .mqtt/MQTTBroker/data:/mosquitto/data
      - .mqtt/MQTTBroker/log:/mosquitto/log

    network_mode: "host"      
  
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    network_mode: "host" 

            
  kafka:
    image: docker.io/bitnami/kafka:3.3
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    network_mode: "host"        
    depends_on:
      - zookeeper


  cloud:
    image: cloud-service 
    depends_on:
      - mosquitto
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      - /bin/sh
      - -c
      - |
        sleep 7
        java -jar /project/cloud-service-1.0-SNAPSHOT-jar-with-dependencies.jar
    network_mode: "host"        
  
  ai-agent:
    image: ai-agent
    depends_on:
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      - /bin/sh
      - -c
      - |
        sleep 7
        python3 -u consumer.py

    network_mode: "host"        
  


  iot-device:
    image: iot-device
    depends_on:
      - cloud
      - mosquitto
    scale: 2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      - /bin/sh
      - -c
      - |
        sleep 7
        python3 -u iot-device.py
